kafka:
  image: spotify/kafka
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    - ADVERTISED_HOST=localhost
    - ADVERTISED_PORT=9092

mongo:
  image: mongo:4.0.9
  ports:
    - "27017:27017"