spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  kafka:
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
        mechanism: SCRAM-SHA-256
      security:
        protocol: SASL_SSL
    bootstrap-servers: ${CLOUDKARAFKA_BROKERS}
    consumer:
      group-id: simian-checker
      auto-offset-reset: earliest
    dna-sample:
      topic: ${CLOUDKARAFKA_TOPIC_PREFIX}dna-samples

  redis:
    url: ${REDIS_URL}
  cache:
    redis:
      time-to-live: 60000